### PR TITLE
first formatting ch18

### PR DESCRIPTION
**Pull request by caliban2**

### CODE REVIEW

**Comment by nomicode** [comment]
https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L26

- [x] this line is too long. text should be hard wraped paras to 79 chars

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L28

- [ ] ~"Table" should be `*Table*`~

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L64

- [ ] ~this should use `--` instead of `:`~

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L66

- [x] this should be a bullet point item 

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L595

- [x] this shouldn't be a bullet point item

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L945

- [x] this is a syntax error (the output formatting breaks). I believe there's some special syntax that allows you to put a literal next to a non-literal, as in "`REF`(UDT)" but I can't remember it off the top of my head

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L990

- [ ] ~the quotes around `bobby` should not be literals (appears elsewhere too)~

**Comment by nomicode** [comment]
https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L1352

- [x] this one is broken (as above)

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L1464

- [x] _SYSTEM should be a literal

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L1809

- [x] "grouped View" should be italics

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2066

- [x] there's a display error with "`NULL`s", like the "`REF`(UDT)" thing (the "s" touching the literal). if you look through some of the earlier chapters, you should be able to find examples of this "`NULL`s" thing done in a way that works that you can just copy for both of these

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2120

- [ ] ~"immediately underlying" should be in italics and not quoted~

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2263

- [x] "Views Hide -- Good" should be in quotes

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2289

- [x] "not" should be in italics

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2304

- [ ] ~"grouped View" should be in italics, not quoted~

https://github.com/crate/sql-99/blob/f4705acd38fd5f102764f8adb140700b4e69d3a3/docs/chapters/18.txt#L2369

- [x] the quote marks should be outside the literal for `_SYSTEM`

**Review by nomicode — CHANGES_REQUESTED** [review]
see above comments :)

**Comment by caliban2** [comment]
open question is:
what takes precedence in cosmetic differences, pdf or source? :) (i.e "Table" vs *Table*)

**Comment by nomicode** [comment]
@caliban2 I think it depends. do you have something specific in mind?

**Pull request merged**
